# Generated by Django 4.1.13 on 2023-12-18 13:36

from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Documents",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=50)),
                ("extenesion", models.CharField(max_length=4)),
                ("create_date", models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
